type: "CNN"
layers:
    conv1:
        type: "CONV"
        specs:  # parameters of tf.layers.conv2d
            kernel_size: [5, 5]
            filters: 32
            padding: "same"
            activation: 'relu'
    pool1:        
        type: "POOL"
        specs:  # parameters of tf.layers.max_pooling2d
            pool_size: [2,2]
            strides: 2
    dense:       
        type: "FC"
        specs:  # parameters of tf.layers.dense
            units: 1024
            activation: 'relu'
    drop:        
        type: "DROP"
        specs:  # tf.layers.dropout
            rate: 0.4
            on_train: True
    logits:
        type: "FC"
        specs:  # parameters of tf.layers.dense
            units: 113
            activation: None
learning_rate: 0.0001
