type: "FC"
layers:
    layer_1:
        type: "FC"
        specs:  # parameters of tf.layers.dense
            units: 1024
            activation: None
    layer_2:
        type: "FC"
        specs:  # parameters of tf.layers.dense
            units: 113
            activation: None
learning_rate: 0.001
